### ISSUE TITLE
Delay in expanding snippets when using auto-trigger

### ISSUE THREAD

**Issue by paniash** [dcampos/nvim-snippy#44] opened 2022-01-17 07:03 UTC
Hi!

Thanks for the implementation of the auto-trigger feature! It works very well but the only issue so far has been the delay it takes for it to start. For example, when launching a latex file (having defined `tex.snippets`), when using snippets using auto-trigger, it doesn't work at all for a couple of seconds. However, after this delay it works very well. The issue is the finite time it takes from launching a file and expanding the snippet.

I know that the help.txt specifies a dip in performance when using auto-trigger. Is it an inherent issue with lua or can it be fixed in the plugin in the future?

**Comment by dcampos** [comment] 2022-01-17 14:21
Hmm, an initial delay isn't something to be expected. The performance issue mentioned in the docs has to do with tracking every text change or typed character. Also, loading the snippets should be fast and is done on `InsertEnter`, so it shouldn't affect performance.

**Comment by dcampos** [comment] 2022-01-18 14:28
I don't know if I can reproduce this. I _think_ it did happen to me once, but now everything works fine when I start Neovim and try to expand an auto-triggered snippet. I can't notice any delay.

Does it occur every time you open a latex file? Is it only with latex files, or it happens with other file types as well? Any additional info would be helpful.

Also, could you try with the minimal config here: https://raw.githubusercontent.com/dcampos/nvim-snippy/master/misc/minimal.vim

**Comment by paniash** [comment] 2022-01-31 15:48
Sorry for the late reply. I was playing around but looks like the delay is event-driven. Only after I launch a snippet that requires `<Tab>` as the trigger, followed by the automatic trigger snippet, does it work.

In other words, trying to launch an automatic snippet as the first snippet after opening a file, does not work until one launches a `<Tab>` (in my case) trigger driven snippet.

**Comment by dcampos** [comment] 2022-02-06 13:31
I still can't reproduce it, so I'm _guessing_ there is an issue/delay when setting up the `autocmds` that trigger the expansion. I'm beginning to think it would be a good idea to change the code to setup the `autocmd`s on startup, instead of only after loading an auto-triggered snippet. I think the auto-trigger feature should be changed to be opt-in then.

**Comment by dcampos** [comment] 2022-04-03 23:40
I've finally gotten around to look into this issue. Although I still couldn't reproduce it, I added an option to enable autotrigger on startup, so there shouldn't be any delay for the `autocmd`s to set up, which hopefully will solve the issue.

To enable autotriger, use the `enable_option` when calling the `setup` method:

```lua
    require('snippy').setup({
        ....
        enable_auto = true,
    })
```

I will close this issue for now, but if anyone still finds bugs with the autotrigger feature, please let me know.

**Closed by dcampos** 2022-04-03 23:40 UTC
Labels: bug, needs repro
